<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="newsletter-iner">
	<div class="container-inner">
		<form class="form-subscribe"
			novalidate
			action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
			method="post"
			data-mage-init='{"validation": {"errorClass": "mage-error"}}'
			id="newsletter-validate-detail">
			<div class="field newsletter">
				<div class="title-new">
					<h3><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletters') ?></h3>
					<p><?php /* @escapeNotVerified */ echo __('Be the First to Know. Sign up for newsletter today') ?></p>
				</div>	
				<div class="control">
					<input name="email" type="email" id="newsletter"
								placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
								data-validate="{required:true, 'validate-email':true}"/>
					<button class="action subscribe" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
						<?php /* @escapeNotVerified */ echo __('Subscribe') ?>
					</button>
				</div>
			</div>

		</form>
	</div>
</div>
