<?php 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$rows = $block->getConfig('row');
	$title = $block->getTitle(); 
	$identify = trim($block->getIdentify()); 
	$categoryIds = $block->getCategoryIds();
	$categoryIds = explode(',', $categoryIds);

	$productsOnRow = 2 ;
	if(!$productsOnRow) $productsOnRow = 3;

?>
<div class="categorytab-container">


 
     <?php 
		
		$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
		$image = 'new_products_content_widget_grid';
		$image2 = 'new_products_content_widget_grid1';
		$type = 'widget-new-grid';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
		$showWishlist = true;
		$showCompare = true;
		$showCart = true;
	?>
	<div class="tab_container"> 
		<?php foreach($categoryIds as $cate_id) { ?>
		<div id="tab<?php echo $cate_id.'-'.$identify;?>" class="tab_content_<?php echo $identify; ?>"> 
		<div class="col-md-2 col-sm-2 col-xs-12 box">
			<header class='group-title1'><?php 	echo '<h2>'.$title.'</h2>'; ?></header>
			<?php 
				$cate_model =  $block->getCategory($cate_id);
				$cat_parent = $cate_model->load($cate_id);
				?>
				<h1><a href="<?php echo $cat_parent->getUrl() ?>"><?php echo $cat_parent->getName() ?></a></h1>
				<?php
				$cats = $this->getcategoriesbyid($cate_id); 
				foreach($cats as $cat){
				?>
					<span><a href="<?php echo $cat->getUrl() ?>"><?php echo $cat->getName(); ?></a></span>
				<?php
				}
				?>
					<a class="all" href="<?php echo $cat_parent->getUrl() ?>"><?php echo __('View All') ?></a>
				<?php
			?>
		</div>
		<div class="col-md-4 col-sm-4 col-xs-12 box">
			<div class="image">
				<?php $cate_image = $block -> getCatetabImage($cat_parent->getCateTab()); ?>
				<img src="<?php echo $cate_image; ?>" alt="<?php echo $cat_parent->getName(); ?>"/>
			</div>
		</div>
		<div class="col-md-6 col-sm-6 col-xs-12 box">
			<div class="saleproducts">
				<?php
				
				$products = $block->getSaleproduct($cate_id);
				$i = 0;
				
				foreach($products as $_item)
				{
				$productImage = $block->getImage($_item, $image2);
				?>
				<div class="item">
					<div class="item-inner">
						
						<div class="image-container ">
							<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
								<?php echo $productImage->toHtml() ?>
							</a>
						</div>
						<div class="des ">
							<div class="product-name">
								<strong class="product-item-name">
									<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
									   href="<?php echo $block->getProductUrl($_item) ?>"
									   class="product-item-link">
										<?php echo $block->escapeHtml($_item->getName()) ?>
									</a>
								</strong>
							</div>
							 <?php
								echo $block->getProductPrice($_item);
							 ?>
							 
							<?php if ($templateType): ?>
								<?php //echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
							<?php endif; ?>
							<div class="actions">
								<?php if ($showCart): ?>
									<div class="actions-primary">
										<?php if ($_item->isSaleable()): ?>
											<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
												<button class="action tocart primary"
														data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
														type="button" title="<?php echo __('Add to Cart') ?>">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											<?php else: ?>
												<?php
													$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
													$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
												?>
												<button class="action tocart"
														data-post='<?php echo $postData; ?>'
														type="button" title="<?php echo __('Add to Cart') ?>">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											<?php endif; ?>
										<?php else: ?>
											<?php if ($_item->getIsSalable()): ?>
												<div class="stock available"><span><?php echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								<?php endif; ?>
								
							</div>
						</div>
					</div>
				</div>
				<?php
				}
				?>
			</div>
			<div class="category_tab_slider_bottom">
				<div class="owl-container">		
					<div class="category_tab_slider owl-carousel">
						<?php 
						$newItems =  $block -> getProductCate2($cate_id)->getItems(); 
						$i=0;
						foreach($newItems as $_item) { 
							$productImage = $block->getImage($_item, $image);
						?>
						<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
							<div class="item">
								<div class="item-inner">
									<div class="product-item-info">		
											<div class="image-container">
												<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
													<?php echo $productImage->toHtml() ?>
												</a>
											</div>
											<div class="product-item-details">
												<div class="product-name">
													<strong class="product-item-name">
														<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
														   href="<?php echo $block->getProductUrl($_item) ?>"
														   class="product-item-link">
															<?php echo $block->escapeHtml($_item->getName()) ?>
														</a>
													</strong>
												</div>
												 <?php
													echo $block->getProductPrice($_item);
												 ?>
												 
												<?php if ($templateType): ?>
													<?php //echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
												<?php endif; ?>
											</div>
											<div class="box-hover clearfix">
												
														<div class="actions-primary">
															<?php if ($_item->isSaleable()): ?>
																<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																	<button class="action tocart primary"
																			data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
																			type="button" title="<?php echo __('Add to Cart') ?>">
																		<span><?php echo __('Add to Cart') ?></span>
																	</button>
																<?php else: ?>
																	<?php
																		$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																		$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																	?>
																	<button class="action tocart"
																			data-post='<?php echo $postData; ?>'
																			type="button" title="<?php echo __('Add to Cart') ?>">
																		<span><?php echo __('Add to Cart') ?></span>
																	</button>
																<?php endif; ?>
															<?php else: ?>
																<?php if ($_item->getIsSalable()): ?>
																	<div class="stock available"><span><?php echo __('In stock') ?></span></div>
																<?php else: ?>
																	<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
																<?php endif; ?>
															<?php endif; ?>
														</div>
													
														<div class="actions-secondary add-to-links" data-role="add-to-links">
															<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
																<a href="#"
																   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
																   class="action towishlist" data-action="add-to-wishlist"
																   title="<?php echo __('Add to Wishlist') ?>">
																	<span><?php echo __('Add to Wishlist') ?></span>
																</a>
															<?php endif; ?>
															<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
																<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
																<a href="#" class="action tocompare"
																   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
																   title="<?php echo __('Add to Compare') ?>">
																	<span><?php echo __('Add to Compare') ?></span>
																</a>
															<?php endif; ?>
														</div>
												
											</div>
									</div>
								</div>
							</div>
								<?php if($i%$rows==0 || $i == count($newItems)) { ?> </div> <?php }?>
						<?php 
						}
						?>
					</div>
				</div>	
			</div>	
		</div>
		
			
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 

</div>
<script type="text/javascript">
require(["jquery", "owlcarousel/minjs"], function($){
	
	$(document).ready(function(){
		$(".tab_content_<?php echo $identify; ?>").hide();
		$(".tab_content_<?php echo $identify; ?>:first").show(); 

		$("ul.tabs<?php echo '-'.$identify;?> li").click(function() {
			$("ul.tabs<?php echo '-'.$identify;?> li").removeClass("active");
			$(this).addClass("active");
			$(".tab_content_<?php echo $identify; ?>").hide();
			var activeTab = $(this).attr("rel"); 
			$("#"+activeTab).fadeIn(); 
		});
		
		 $(".tab_content_<?php echo $identify; ?> .category_tab_slider").owlCarousel({
					items : 3,
			autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
			slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
			navigation : <?php if($show_navigation) echo 'true'; else echo 'false'; ?>,
			stopOnHover : true,
			pagination : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
			itemsDesktop : [1199,3],
			itemsDesktopSmall : [992,2],
			itemsTablet: [767,2],
			itemsMobile : [479,1]
		});
		
		$(".tab_content_<?php echo $identify; ?> .saleproducts").owlCarousel({
					items : 1,
			autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
			slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
			navigation : <?php if($show_navigation) echo 'true'; else echo 'false'; ?>,
			stopOnHover : true,
			pagination : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
			itemsDesktop : [1199,1],
			itemsDesktopSmall : [992,1],
			itemsTablet: [767,1],
			itemsMobile : [479,1]
		});
	});
	
});
 

</script> 
