<?php 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$itemsDefault = $block->getConfig('itemsDefault');
	$itemsDesktop = $block->getConfig('itemsDesktop');
	$itemsDesktopSmall = $block->getConfig('itemsDesktopSmall');
	$itemsTablet = $block->getConfig('itemsTablet');
	$itemsMobile = $block->getConfig('itemsMobile');
	$title = $block->getConfig('title');
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$rows = $block->getConfig('row');
	if($rows == 0)
		$rows = 1;	
?>
<div class="onsaleproduct_container_slider ">
	
		<header class='group-title1 ma-title'><h2><?php echo $title;?> </h2></header>
		
		<div class="countbox-sale-one countdown-container" id="countbox-sale-one">
			<div class='datetime'>
				<span class='day'><?php echo __('D') ?></span>
				<span class='hour'><?php echo __('H') ?></span>
				<span class='min'><?php echo __('M') ?></span>
				<span class='sec'><?php echo __('S') ?></span>
			</div>
		</div>
		
		<div class="owl-container">
			<div id="sale_product_slider" class="owl-carousel">
				<?php 
				$saleItems =  $block -> getSaleProduct()->getItems(); 
				$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
				$image = 'new_products_content_widget_grid';
				$type = 'widget-new-grid';
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
				$i=0;
				foreach($saleItems as $_item) { 
						$productImage = $block->getImage($_item, $image);
					?>
					<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php $count_r = 0; } ?>
					<div class="item">
						<div class="item-inner <?php if($count_r == 0) echo 'first'; ?><?php if($count_r == 2) echo 'last'; ?>">
							<?php $count_r++; ?>
							<div class="image-container product-item-info">
								<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
									<?php echo $productImage->toHtml() ?>
								</a>
								<div class="product-item-details">
								
										<div class="product-name">
											<strong class="product-item-name">
												<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
												   href="<?php echo $block->getProductUrl($_item) ?>"
												   class="product-item-link">
													<?php echo $block->escapeHtml($_item->getName()) ?>
												</a>
											</strong>
										</div>
										<?php if ($templateType): ?>
											<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
										<?php endif; ?>
										 <?php
											echo $block->getProductPrice($_item);
										 ?>
								</div>
								<div class="box-hover">
									<?php if ($showCart): ?>
										<div class="actions-primary">
											<?php if ($_item->isSaleable()): ?>
												<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
													<button class="action tocart primary"
															data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
															type="button" title="<?php echo __('Add to Cart') ?>">
														<span><?php echo __('Add to Cart') ?></span>
													</button>
												<?php else: ?>
													<?php
														$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
													?>
													<button class="action tocart primary"
															data-post='<?php echo $postData; ?>'
															type="button" title="<?php echo __('Add to Cart') ?>">
														<span><?php echo __('Add to Cart') ?></span>
													</button>
												<?php endif; ?>
											<?php else: ?>
												<?php if ($_item->getIsSalable()): ?>
													<div class="stock available"><span><?php echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php endif; ?>
									<?php if ($showWishlist || $showCompare): ?>
										<div class="add-to-links" data-role="add-to-links">
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
												<a href="#"
												   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
												   class="action towishlist" data-action="add-to-wishlist"
												   title="<?php echo __('Add to Wishlist') ?>">
													<span><?php echo __('Add to Wishlist') ?></span>
												</a>
											<?php endif; ?>
											<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
												<a href="#" class="action tocompare"
												   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
												   title="<?php echo __('Add to Compare') ?>">
													<span><?php echo __('Add to Compare') ?></span>
												</a>
											<?php endif; ?>
										</div>
									<?php endif; ?>
								</div>
							</div>
							
						</div>
						
					</div>
					<?php if($i%$rows==0 || $i == count($saleItems)) { ?> </div> <?php }?>
				<?php 
				}
				?>
			</div>
		</div>	
	
	<?php
		$toDate = $_item->getSpecialToDate();
		$fromDate = $_item->getSpecialFromDate();
		$_current_timer = time();
	?>
	<script type="text/javascript">
		var dthen<?php echo $_item->getId(); ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)).' 11:59:00 PM'; ?>");
		var start = "<?php echo Date("m/d/y h:i:s A", $_current_timer); ?>";
		var start_date = Date.parse(start);
		var dnow<?php echo $_item->getId(); ?> = new Date(start_date);

		var ddiff;
		if(CountStepper > 0) {
			ddiff= new Date((dnow<?php echo $_item->getId(); ?>)-(dthen<?php echo $_item->getId(); ?>));
		} else {
			ddiff = new Date((dthen<?php echo $_item->getId(); ?>)-(dnow<?php echo $_item->getId(); ?>));
		}

		<?php if(strtotime($fromDate) <= $_current_timer): ?>
			gsecs<?php echo $_item->getId(); ?> = Math.floor(ddiff.valueOf()/1000);
		<?php else: ?>
			gsecs<?php echo $_item->getId(); ?> = -1;
		<?php endif; ?>
		if(gsecs<?php echo $_item->getId(); ?> < 0)
			gsecs<?php echo $_item->getId(); ?> = - gsecs<?php echo $_item->getId(); ?>;
		var iid<?php echo $_item->getId(); ?> = "countbox-sale-one";
		CountBack_slider(gsecs<?php echo $_item->getId(); ?>,"countbox-sale-one", <?php echo $_item->getId(); ?>);
	</script>
	
</div>
<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
	
   $("#sale_product_slider").owlCarousel({ 
		autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
		slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
		navigation : <?php if($show_navigation) echo 'true'; else echo 'false'; ?>,
		stopOnHover : true,
		pagination : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
		items : <?php if($itemsDefault) echo $itemsDefault; else echo '4'; ?>,
		itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '4'; ?>],
		itemsDesktopSmall : [992,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
		itemsTablet: [767,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
		itemsMobile : [479,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
   });
   
});
</script>      